// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BrokerWallet struct {
	Amount *float64 `json:"amount"`
}

type Wallet struct {
	TotalAmount   *float64        `json:"totalAmount"`
	BrokerWallets []*BrokerWallet `json:"brokerWallets"`
}
