// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Wallet struct {
	TotalAvailableAmount []*WalletBrokerWalletCoinItem `json:"totalAvailableAmount"`
	TotalReservedAmount  []*WalletBrokerWalletCoinItem `json:"totalReservedAmount"`
	BrokerWallets        []*WalletBrokerWallet         `json:"brokerWallets"`
}

type WalletBrokerWallet struct {
	DomainCode string                        `json:"domainCode"`
	Available  []*WalletBrokerWalletCoinItem `json:"Available"`
	Reserved   []*WalletBrokerWalletCoinItem `json:"Reserved"`
}

type WalletBrokerWalletCoinItem struct {
	Coin   string  `json:"Coin"`
	Amount float64 `json:"Amount"`
}
